const app=getApp()
const {createScopedThreejs}=require('threejs-miniprogram')
const {DRINKS,STYLE_MODES,getDrunkLevel,getRandomQuote,checkAchievements}=require('../../utils/drinks.js')
const {getV7Profile}=require('../../utils/v7DrinkProfiles.js')
const audio=require('../../utils/audio.js')
const hex=(v,d)=>{const n=parseInt(String(v||'').replace('#','').slice(0,6),16);return Number.isFinite(n)?n:d}
Page({
 data:{drinks:DRINKS,drink:DRINKS[0],profile:getV7Profile('beer'),activeIndex:0,ready:false,busy:false,cocktailCrafted:false,sips:0,glasses:0,drunkValue:0,drunkStatus:'清醒',drunkLevelColor:'#5DCAA5',currentQuote:'拖动场景可以转动视角',quoteVisible:true,themeStyle:''},
 onLoad(o){const id=o.id||'beer',i=Math.max(0,DRINKS.findIndex(x=>x.id===id)),drink=DRINKS[i];this.session=[drink.id];this.breakdown={[drink.id]:{sips:0,glasses:0}};this.setData({drink,profile:getV7Profile(id),activeIndex:i,cocktailCrafted:o.crafted==='1'});const m=STYLE_MODES[app.globalData.styleMode||'heroic'];if(m)this.setData({themeStyle:`--accent:${m.theme.accent};--text-main:${m.theme.text};--text-sub:${m.theme.textSub}`})},
 onReady(){wx.createSelectorQuery().select('#drink3d').fields({node:true,size:true}).exec(r=>{if(!r[0])return;this.canvas=r[0].node;this.canvas.width=r[0].width;this.canvas.height=r[0].height;this.THREE=createScopedThreejs(this.canvas);this.build3D();this.setData({ready:true});this.quote('真 3D 酒桌已就绪 · 拖动可换视角')})},
 onShow(){audio.resumeMusic()},onHide(){audio.pauseMusic()},onUnload(){clearTimeout(this.qt);clearTimeout(this.at);if(this.world)this.world.dead=true;audio.pauseMusic()},
 mat(c,o={}){const T=this.THREE;return new T.MeshStandardMaterial({color:c,roughness:o.r==null?.3:o.r,metalness:o.m||0,transparent:!!o.t,opacity:o.o==null?1:o.o,side:o.ds?T.DoubleSide:T.FrontSide})},
 bottle(){const T=this.THREE,p=this.data.profile,g=new T.Group(),kind=p.bottle.kind,c=hex(p.bottle.body,0x604020),m=this.mat(c,{r:.2,t:kind.includes('bottle'),o:.86}),cm=this.mat(hex(p.bottle.cap,0xd9b56f),{r:.25,m:.3});let b;if(kind==='whiskey_bottle')b=new T.Mesh(new T.BoxGeometry(.82,1.65,.62),m);else if(kind==='beer_can')b=new T.Mesh(new T.CylinderGeometry(.38,.38,1.75,28),m);else b=new T.Mesh(new T.CylinderGeometry(.4,.5,1.8,28),m);b.position.y=.92;b.castShadow=true;g.add(b);const nr=kind==='beer_can'?.31:.18,nh=kind==='beer_can'?.14:.72,n=new T.Mesh(new T.CylinderGeometry(nr,nr*1.08,nh,20),m);n.position.y=kind==='beer_can'?1.86:2.18;g.add(n);const cap=new T.Mesh(new T.CylinderGeometry(nr*1.1,nr*1.1,.11,20),cm);cap.position.y=kind==='beer_can'?1.99:2.59;g.add(cap);return g},
 glass(){const T=this.THREE,d=this.data.drink,g=new T.Group(),gm=this.mat(0xdce8ef,{r:.04,t:true,o:.24,ds:true}),lm=this.mat(hex(d.color,0xc87938),{r:.12,t:true,o:.82});let body,r=.42,h=1.05,base=.12;if(d.glassType==='beer_mug'){body=new T.Mesh(new T.CylinderGeometry(.58,.5,1.75,30,1,true),gm);body.position.y=.88;const handle=new T.Mesh(new T.TorusGeometry(.48,.07,10,28,Math.PI*1.45),gm);handle.position.set(.56,.95,0);handle.rotation.y=Math.PI/2;handle.rotation.z=-2.2;g.add(handle);r=.45;h=1.48;base=.14}else if(d.glassType==='rocks_glass'){body=new T.Mesh(new T.CylinderGeometry(.62,.56,1.02,30,1,true),gm);body.position.y=.53;r=.52;h=.8;base=.13}else if(d.glassType==='shot_glass'||d.glassType==='erguotou_glass'){body=new T.Mesh(new T.CylinderGeometry(.35,.27,.7,26,1,true),gm);body.position.y=.37;r=.27;h=.5;base=.11}else if(d.glassType==='wine_glass'){const bowl=new T.Mesh(new T.SphereGeometry(.64,28,18,0,Math.PI*2,0,Math.PI*.66),gm);bowl.scale.set(.78,1.05,.78);bowl.position.y=1.13;g.add(bowl);const stem=new T.Mesh(new T.CylinderGeometry(.04,.04,.78,14),gm);stem.position.y=.44;g.add(stem);const foot=new T.Mesh(new T.CylinderGeometry(.4,.4,.05,24),gm);foot.position.y=.03;g.add(foot);r=.4;h=.55;base=.86}else if(d.glassType==='cocktail_glass'){body=new T.Mesh(new T.CylinderGeometry(.7,.08,.8,30,1,true),gm);body.position.y=1.16;const stem=new T.Mesh(new T.CylinderGeometry(.04,.04,.78,14),gm);stem.position.y=.47;g.add(stem);const foot=new T.Mesh(new T.CylinderGeometry(.42,.42,.05,24),gm);foot.position.y=.03;g.add(foot);r=.38;h=.43;base=.9}else{body=new T.Mesh(new T.CylinderGeometry(.5,.42,1.2,30,1,true),gm);body.position.y=.62}if(body)g.add(body);const liq=new T.Mesh(new T.CylinderGeometry(r,r*.94,h,28),lm);liq.scale.y=.01;liq.position.y=base;g.add(liq);g.userData={liq,base,h};return g},
 setLiquid(v){if(!this.g3)return;v=Math.max(.01,Math.min(1,v));this.level=v;const u=this.g3.userData;u.liq.scale.y=v;u.liq.position.y=u.base+u.h*v*.5},
 build3D(){const T=this.THREE,C=this.canvas,S=new T.Scene();S.background=new T.Color(0x080a10);S.fog=new T.Fog(0x080a10,8,18);const cam=new T.PerspectiveCamera(42,C.width/C.height,.1,50);cam.position.set(0,3.1,8.6);cam.lookAt(0,1.2,0);const R=new T.WebGLRenderer({antialias:true});R.setPixelRatio(Math.min(wx.getSystemInfoSync().pixelRatio||1,2));R.setSize(C.width,C.height);R.shadowMap.enabled=true;S.add(new T.AmbientLight(0x7888aa,.7));const w=new T.PointLight(0xffb166,1.8,16);w.position.set(-3.5,5.5,4);S.add(w);const c=new T.PointLight(0x79a8ff,1.1,14);c.position.set(4,3,2);S.add(c);const root=new T.Group();S.add(root);const table=new T.Mesh(new T.CylinderGeometry(4.4,4.6,.36,56),this.mat(0x281c18,{r:.58}));table.position.y=-.22;table.receiveShadow=true;root.add(table);const back=new T.Mesh(new T.BoxGeometry(9,4.5,.3),this.mat(0x10151f,{r:.75}));back.position.set(0,2,-3.6);root.add(back);const b=this.bottle();b.position.set(-1.7,0,.12);root.add(b);const g=this.glass();g.position.set(1.2,0,.18);root.add(g);const stream=new T.Mesh(new T.CylinderGeometry(.045,.035,2.1,10),this.mat(hex(this.data.drink.color,0xc87938),{r:.1,t:true,o:.78}));stream.visible=false;root.add(stream);this.g3=g;this.level=0;this.world={S,cam,R,root,b,g,stream,phase:'idle',dead:false,yaw:0,desiredYaw:0};this.animate3D()},
 animate3D(){const W=this.world,C=this.canvas;if(!W||W.dead)return;W.yaw+=(W.desiredYaw-W.yaw)*.08;W.root.rotation.y=W.yaw;if(W.phase==='pour'){const t=Math.min(1,(Date.now()-W.t0)/W.dur),a=Math.max(0,Math.min(1,t/.25,(1-t)/.16));W.b.rotation.z=-1*a;W.b.position.set(-1.7+.75*a,.45*a,.12);W.stream.visible=t>.22&&t<.86;if(W.stream.visible){W.stream.position.set(.1,1.65,.12);W.stream.rotation.z=-.55;W.stream.scale.y=.9}const f=Math.max(0,Math.min(1,(t-.22)/.62));this.setLiquid(W.start+(W.target-W.start)*f);if(t>=1){W.b.rotation.z=0;W.b.position.set(-1.7,0,.12);W.stream.visible=false;W.phase='idle'}}else if(W.phase==='drink'){const t=Math.min(1,(Date.now()-W.t0)/W.dur),a=t<.3?t/.3:t<.72?1:(1-t)/.28;W.g.position.set(1.2-.62*a,1.55*a,.18+.48*a);W.g.rotation.z=-.72*a;W.g.rotation.x=.16*a;if(t>.34&&t<.76)this.setLiquid(Math.max(0,W.start-W.amount*((t-.34)/.42)));if(t>=1){W.g.position.set(1.2,0,.18);W.g.rotation.set(0,0,0);this.setLiquid(Math.max(0,W.start-W.amount));W.phase='idle'}}C.requestAnimationFrame(()=>this.animate3D());W.R.render(W.S,W.cam)},
 startPour(){const W=this.world,p=this.data.profile;if(!W||W.phase!=='idle'||this.data.busy)return;if(p.requiresBartending&&!this.data.cocktailCrafted){this.goBartend();return}if(this.level>.12){this.quote('杯里还有酒，先喝完再倒');return}W.phase='pour';W.t0=Date.now();W.dur=p.pour.duration||1800;W.start=this.level;W.target=p.fillTarget||.75;this.setData({busy:true});audio.playSfx('pour');wx.vibrateShort({type:'light'});clearTimeout(this.at);this.at=setTimeout(()=>{this.setData({busy:false});this.quote(p.pour.caption||'倒好了')},W.dur+100)},
 takeSip(){const W=this.world,d=this.data.drink,p=this.data.profile;if(!W||W.phase!=='idle'||this.data.busy||this.data.drunkValue>=100)return;if(this.level<=.04){this.quote('先倒一杯');return}const amount=Math.min(.32,1/d.sipsPerGlass+(d.abv>=40?.05:0)),dur=p.motion.duration||1200;W.phase='drink';W.t0=Date.now();W.dur=dur;W.start=this.level;W.amount=amount;const nv=Math.min(100,this.data.drunkValue+(100/d.sipsPerGlass)*d.drunkSpeed*.35),lv=getDrunkLevel(nv),br=this.breakdown[d.id]||{sips:0,glasses:0};br.sips++;this.breakdown[d.id]=br;this.setData({busy:true,sips:this.data.sips+1,drunkValue:Math.round(nv),drunkStatus:lv.status,drunkLevelColor:lv.color});audio.playSfx('drink');clearTimeout(this.at);this.at=setTimeout(()=>{if(this.level<=.04){br.glasses++;this.setData({glasses:this.data.glasses+1})}this.setData({busy:false});this.quote(getRandomQuote(nv,d.id));if(nv>=100)setTimeout(()=>this.finishDrinking(),900)},dur+100)},
 switchDrink(e){const i=Number(e.currentTarget.dataset.index);if(!Number.isFinite(i)||i===this.data.activeIndex||this.data.busy)return;if(this.level>.04){wx.showModal({title:'杯里还有酒',content:'换酒会撤下这一杯，确定换吗？',success:r=>{if(r.confirm)this.applyDrink(i)}})}else this.applyDrink(i)},
 applyDrink(i){const d=DRINKS[i],p=getV7Profile(d.id);if(!this.session.includes(d.id))this.session.push(d.id);if(!this.breakdown[d.id])this.breakdown[d.id]={sips:0,glasses:0};if(this.world)this.world.dead=true;this.setData({drink:d,profile:p,activeIndex:i,cocktailCrafted:d.id==='cocktail'?false:this.data.cocktailCrafted},()=>this.build3D());app.globalData.currentDrink=d;audio.playSfx('click');this.quote(`换成${d.name} · ${p.serving}`)},
 goBartend(){app.globalData.currentDrink=this.data.drink;wx.navigateTo({url:'/pages/bartend-3d/bartend-3d'})},
 onTouchStart(e){const t=e.touches&&e.touches[0];if(!t)return;const x=t.x==null?(t.clientX==null?t.pageX:t.clientX):t.x;this.tx=x||0;this.y0=this.world?this.world.desiredYaw||0:0},onTouchMove(e){const t=e.touches&&e.touches[0];if(!t||!this.world)return;const x=t.x==null?(t.clientX==null?t.pageX:t.clientX):t.x;this.world.desiredYaw=Math.max(-.5,Math.min(.5,this.y0+((x||0)-this.tx)/220))},
 quote(s){clearTimeout(this.qt);this.setData({currentQuote:s,quoteVisible:true});this.qt=setTimeout(()=>this.setData({quoteVisible:false}),2800)},
 finishDrinking(){const st=app.globalData.stats;st.totalSips+=this.data.sips;st.totalDrinks+=this.data.glasses;st.maxDrunkLevel=Math.max(st.maxDrunkLevel,this.data.drunkValue);st.drinkRecords=st.drinkRecords||[];Object.keys(this.breakdown).forEach(id=>{const x=this.breakdown[id];if(x.sips||x.glasses)st.drinkRecords.push({drinkId:id,sips:x.sips,glasses:x.glasses,drunkLevel:this.data.drunkValue,time:Date.now()})});const ach=checkAchievements(st);app.saveStats();app.globalData.finishData={drink:this.data.drink,sips:this.data.sips,glasses:this.data.glasses,drunkValue:this.data.drunkValue,breakdown:this.breakdown,newAchievements:ach};wx.redirectTo({url:'/pages/result/result'})},
 onShareAppMessage(){return{title:`我正在 3D 赛博酒桌喝${this.data.drink.name}`,path:`/pages/drink-3d/drink-3d?id=${this.data.drink.id}`}}
})
