const app=getApp()
const {createScopedThreejs}=require('threejs-miniprogram')
const {BASE_LIQUORS,MIXERS}=require('../../utils/drinks.js')
const audio=require('../../utils/audio.js')
Page({
 data:{bases:BASE_LIQUORS,mixers:MIXERS,step:0,ready:false,busy:false,base:-1,mixer:-1,shakeCount:0,finished:false,stepName:'量取基酒',hint:'选择基酒，调酒师会先用量酒器量取'},
 onReady(){wx.createSelectorQuery().select('#bar3d').fields({node:true,size:true}).exec(r=>{if(!r[0])return;this.canvas=r[0].node;this.canvas.width=r[0].width;this.canvas.height=r[0].height;this.T=createScopedThreejs(this.canvas);this.build();this.setData({ready:true})})},
 onShow(){audio.resumeMusic()},onHide(){this.stopAccel();audio.pauseMusic()},onUnload(){this.stopAccel();clearTimeout(this.tm);if(this.w)this.w.dead=true;audio.pauseMusic()},
 mat(c,o={}){const T=this.T;return new T.MeshStandardMaterial({color:c,roughness:o.r==null?.28:o.r,metalness:o.m||0,transparent:!!o.t,opacity:o.o==null?1:o.o,side:o.ds?T.DoubleSide:T.FrontSide})},
 cyl(r1,r2,h,c,o){const T=this.T;return new T.Mesh(new T.CylinderGeometry(r1,r2,h,28,1,false),this.mat(c,o))},
 build(){const T=this.T,C=this.canvas,S=new T.Scene();S.background=new T.Color(0x090b11);const cam=new T.PerspectiveCamera(42,C.width/C.height,.1,50);cam.position.set(0,3.3,8.8);cam.lookAt(0,1.1,0);const R=new T.WebGLRenderer({antialias:true});R.setPixelRatio(Math.min(wx.getSystemInfoSync().pixelRatio||1,2));R.setSize(C.width,C.height);R.shadowMap.enabled=true;S.add(new T.AmbientLight(0x8290ad,.72));const a=new T.PointLight(0xffb56f,1.9,16);a.position.set(-3,5,4);S.add(a);const b=new T.PointLight(0x78a8ff,1.2,14);b.position.set(4,3,2);S.add(b);const root=new T.Group();S.add(root);const bar=new T.Mesh(new T.BoxGeometry(9,.42,4.7),this.mat(0x2b1b17,{r:.58}));bar.position.y=-.25;root.add(bar);const shaker=new T.Group(),cup=this.cyl(.48,.38,1.55,0xbfc7cf,{r:.18,m:.72});cup.position.y=.78;shaker.add(cup);const lid=this.cyl(.33,.5,.62,0xd8dde1,{r:.16,m:.75});lid.position.y=1.84;shaker.add(lid);shaker.position.set(0,0,.1);root.add(shaker);const jigger=new T.Group(),j1=this.cyl(.29,.17,.48,0xd8dde1,{r:.12,m:.8}),j2=this.cyl(.22,.14,.38,0xc9d0d6,{r:.12,m:.8});j1.position.y=.47;j2.position.y=.06;j2.rotation.z=Math.PI;jigger.add(j1,j2);jigger.position.set(-1.2,0,.2);root.add(jigger);const bottle=this.cyl(.4,.48,1.7,0x44613c,{r:.18,t:true,o:.84});bottle.position.set(-2.5,.86,.1);root.add(bottle);const neck=this.cyl(.18,.2,.72,0x44613c,{r:.18,t:true,o:.84});neck.position.set(-2.5,2.05,.1);root.add(neck);const glass=new T.Group(),gm=this.mat(0xdce8ef,{r:.04,t:true,o:.24,ds:true}),bowl=new T.Mesh(new T.CylinderGeometry(.68,.1,.82,30,1,true),gm);bowl.position.y=1.18;glass.add(bowl);const stem=this.cyl(.04,.04,.8,0xdce8ef,{r:.04,t:true,o:.3});stem.position.y=.48;glass.add(stem);const foot=this.cyl(.42,.42,.05,0xdce8ef,{r:.04,t:true,o:.3});foot.position.y=.03;glass.add(foot);const liq=this.cyl(.38,.12,.44,0xd47e63,{r:.1,t:true,o:.82});liq.position.y=1.12;liq.scale.y=.01;glass.add(liq);glass.position.set(2.1,0,.1);root.add(glass);const ice=[];for(let i=0;i<5;i++){const q=new T.Mesh(new T.BoxGeometry(.28,.28,.28),this.mat(0xcde9f2,{r:.05,t:true,o:.55}));q.position.set(-.35+i*.17,3.5+(i%2)*.3,.1);q.visible=false;root.add(q);ice.push(q)}const garnish=new T.Mesh(new T.TorusGeometry(.22,.045,10,28),this.mat(0x79b84a,{r:.5}));garnish.position.set(2.46,1.55,.1);garnish.rotation.x=Math.PI/2;garnish.visible=false;root.add(garnish);this.w={S,cam,R,root,shaker,jigger,bottle,neck,glass,liq,ice,garnish,phase:'idle',dead:false};this.anim()},
 anim(){const W=this.w,C=this.canvas;if(!W||W.dead)return;const now=Date.now(),t=W.phase==='idle'?0:Math.min(1,(now-W.t0)/W.dur);if(W.phase==='measure'){const a=t<.4?t/.4:t<.7?1:(1-t)/.3;W.bottle.rotation.z=-1*a;W.bottle.position.x=-2.5+1.05*a;W.neck.rotation.z=-1*a;W.neck.position.x=-2.5+1.05*a;W.jigger.position.y=.55*a;if(t>=1)this.donePhase()}else if(W.phase==='ice'){W.ice.forEach((q,i)=>{q.visible=true;const p=Math.max(0,Math.min(1,t*1.5-i*.12));q.position.y=3.5*(1-p)+(.45+i*.12)*p;q.position.x=(-.35+i*.17)*(1-p)});if(t>=1)this.donePhase()}else if(W.phase==='mixer'){const a=t<.35?t/.35:t<.75?1:(1-t)/.25;W.bottle.rotation.z=-.9*a;W.bottle.position.x=-2.5+1.8*a;W.neck.rotation.z=-.9*a;W.neck.position.x=-2.5+1.8*a;if(t>=1)this.donePhase()}else if(W.phase==='shake'){const a=Math.sin(t*Math.PI*12)*(1-t*.2);W.shaker.position.set(a*.78,.5+Math.abs(a)*.18,.1);W.shaker.rotation.z=a*.3;if(t>=1){W.shaker.position.set(0,0,.1);W.shaker.rotation.z=0;this.donePhase()}}else if(W.phase==='strain'){const a=t<.35?t/.35:t<.82?1:(1-t)/.18;W.shaker.position.set(1.15*a,1.25*a,.1);W.shaker.rotation.z=-1.05*a;W.liq.scale.y=Math.max(.01,(t-.25)/.55);if(t>=1){W.shaker.position.set(0,0,.1);W.shaker.rotation.z=0;W.liq.scale.y=1;this.donePhase()}}else if(W.phase==='garnish'){W.garnish.visible=true;const a=Math.min(1,t*1.7);W.garnish.position.y=3.2*(1-a)+1.55*a;W.garnish.rotation.z+=.08;if(t>=1)this.donePhase()}C.requestAnimationFrame(()=>this.anim());W.R.render(W.S,W.cam)},
 phase(name,dur,cb){if(!this.w||this.w.phase!=='idle'||this.data.busy)return false;this.w.phase=name;this.w.t0=Date.now();this.w.dur=dur;this.phaseCallback=cb;this.setData({busy:true});return true},donePhase(){const cb=this.phaseCallback;this.phaseCallback=null;this.w.phase='idle';this.setData({busy:false});if(cb)cb()},
 selectBase(e){const i=Number(e.currentTarget.dataset.i);if(this.data.step!==0||this.data.busy)return;this.setData({base:i});if(this.phase('measure',1500,()=>this.next())){audio.playSfx('pour');wx.vibrateShort({type:'light'})}},addIce(){if(this.data.step!==1)return;if(this.phase('ice',1300,()=>this.next()))audio.playSfx('click')},selectMixer(e){const i=Number(e.currentTarget.dataset.i);if(this.data.step!==2||this.data.busy)return;this.setData({mixer:i});if(this.phase('mixer',1500,()=>this.next()))audio.playSfx('pour')},startShake(){if(this.data.step!==3||this.data.busy)return;if(this.phase('shake',1900,()=>{this.stopAccel();this.next()})){audio.playSfx('shake');this.startAccel()}},
 startAccel(){this.stopAccel();this.acc=e=>{const m=Math.sqrt(e.x*e.x+e.y*e.y+e.z*e.z);if(m>1.8&&!this.deb){this.deb=true;this.setData({shakeCount:Math.min(5,this.data.shakeCount+1)});wx.vibrateShort({type:'light'});setTimeout(()=>this.deb=false,250)}};wx.startAccelerometer({interval:'game'});wx.onAccelerometerChange(this.acc)},stopAccel(){if(this.acc){wx.stopAccelerometer();wx.offAccelerometerChange(this.acc);this.acc=null}},strain(){if(this.data.step!==4)return;if(this.phase('strain',1800,()=>this.next()))audio.playSfx('pour')},garnish(){if(this.data.step!==5)return;if(this.phase('garnish',1200,()=>{this.setData({finished:true,stepName:'完成',hint:'你的鸡尾酒已经制作完成'});audio.playSfx('achievement')}))audio.playSfx('click')},
 next(){const s=this.data.step+1,n=['量取基酒','加入冰块','加入辅料','摇壶','滤冰出酒','最后装饰'][s]||'完成',h=['选择基酒，先用 Jigger 量取','把冰块加入 Shaker','选择一款辅料加入','摇动手机，看调酒师摇壶','将酒过滤倒入杯中','放上最后的 Garnish'][s]||'';this.setData({step:s,stepName:n,hint:h})},goDrink(){wx.redirectTo({url:'/pages/drink-3d/drink-3d?id=cocktail&crafted=1'})}
})
